# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

require: test/support
check-leaks: true
ui: bdd
slow: 100
timeout: 2000
reporter: spec
spec: test/**/*.spec.js
package: ./package.json
extension: [ js ]